import 'easymde/dist/easymde.min.css';
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from '@/components/navbar';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import AuthProvider from '@/providers/auth-provider';
import QueryProvider from '@/providers/query-provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={inter.variable} suppressHydrationWarning>
      <body className={`antialiased`}>
        <div className='flex flex-col h-screen'>
          <AuthProvider>
            <QueryProvider>
              <ThemeProvider
                attribute='class'
                defaultTheme='system'
                // enableSystem
                // disableTransitionOnChange
              >
                <Toaster richColors position='bottom-right' />
                <Navbar />
                <main className='container mx-auto flex-1 py-6'>
                  {children}
                </main>
              </ThemeProvider>
            </QueryProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
