// @ts-expect-error - global CSS side-effect import has no type declarations
import './globals.css';
import 'easymde/dist/easymde.min.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from '@/components/navbar';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={inter.variable} suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          // enableSystem
          // disableTransitionOnChange
        >
          <Navbar />
          <main className='px-4'>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
